trigger: none

variables:
    dockerRegistryServiceConnection: 'Devops-Clinic-CR-Connection'
    imageRepository: 'devopsclinicdemo'
    containerRegistry: 'devopsclinic.azurecr.io'
    imagePullSecret: clinicimage

resources:
  containers:
  - container: devopsclinincdemo
    type: ACR
    azureSubscription: Azure-Resource-Manager-Connection
    resourceGroup: anraghun
    registry: devopsClinic
    repository: devopsclinicdemo
    trigger: true

stages:

- stage: Deploy
  displayName: 'Deploy to Production'
  pool:
    vmImage: 'ubuntu-latest'

  jobs:

  - deployment: DeployToAks
    displayName: 'Deploy to Azure Kubernetes Service'
    environment: 'Devops-Clinic-Environment.devops-clinic'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: "devops-clinic"
              secretName: $(imagePullSecret)              
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: "devops-clinic"
              manifests: |
                $(System.DefaultWorkingDirectory)/manifests/deployment.yml
                $(System.DefaultWorkingDirectory)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)