# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
    dockerRegistryServiceConnection: 'Devops-Clinic-CR-Connection'
    imageRepository: 'devopsclinicdemo'
    containerRegistry: 'devopsclinic.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'
    tag: '$(Build.BuildId)'

stages:

- stage: Build_And_Test
  displayName: 'Build And Test'
  pool:
    vmImage: 'ubuntu-latest'

  jobs:

  - job: Build
    displayName: 'Install Dependencies and Test'
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      inputs:
        command: 'install'
      displayName: 'Npm Install'

    - script: |
        npm test        
      displayName: 'Test'

- stage: Containerise_And_Push
  displayName: 'Containerise and Push Image'
  dependsOn: Build_And_Test
  pool:
    vmImage: 'ubuntu-latest'

  jobs:

  - job: Build_And_Push
    displayName: 'Build Container Image and Push to Registry'
    steps:

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
    
