# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:

- stage: Build_And_Test
  displayName: 'Build And Test'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    displayName: 'Install Dependencies and Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - task: Npm@1
      inputs:
        command: 'install'
    - script: |
        npm run build
      displayName: 'Build'

  - job: Test
    dependsOn: Build
    displayName: 'Run Tests'
    steps:
    - script: |
        npm test        
      displayName: 'Test'
